server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: fullstackauth

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DB_INSTITUTO
    username: puente
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: XRZiou1NLAT6U9by3i9BqZU177pIGJDM
            client-secret: miClientSecretDePrueba123!
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth0:
            issuer-uri: https://dev-ld3puk3zorfr3szr.us.auth0.com/

      resourceserver:
        jwt:
          issuer-uri: https://dev-ld3puk3zorfr3szr.us.auth0.com/

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
